class LikertScale
  STRONGLY_DISAGREE = 0
  SOMEWHAT_DISAGREE = 1
  UNDECIDED = 2
  SOMEWHAT_AGREE = 3
  STRONGLY_AGREE = 4

  SCORES = [STRONGLY_DISAGREE, SOMEWHAT_DISAGREE, UNDECIDED, SOMEWHAT_AGREE, STRONGLY_AGREE]
end
